## Numpy:

#### Criação de arrays: np.array()    
                   
* Verificar a dimensão: np.ndim()                     
* Verificar tamanho: np.size()                        
* Verificar forma: np.shape()                         


In [25]:
import numpy as np

a = np.array([1,2,3])
print("Array: %s, Dimensão: %d, Tamanho: %d, Forma: %s" % (a, np.ndim(a), np.size(a), np.shape(a)))

Array: [1 2 3], Dimensão: 1, Tamanho: 3, Forma: (3,)


#### Criação de array multidimensionais:

A função np.array() aceitará mais linhas de valores para criar array de mais dimensões

In [26]:
import numpy as np

b = np.array([[1,2],[0,4]])
print("Array: %s, Dimensão: %d, Tamanho: %d, Forma: %s" % (b, np.ndim(b), np.size(b), np.shape(b)))

Array: [[1 2]
 [0 4]], Dimensão: 2, Tamanho: 4, Forma: (2, 2)


Numpy aceita vários tipo de dados, como: int, floar, bool, complex, string, etc.

Recebendo dados do tipo complex, pode-se criar Arrays com valores complexos

In [27]:
import numpy as np

f = np.array([[1,2,3],[4,5,6]], dtype=complex)
print(f)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


#### Formas Íntrinsecas de criar Array:

Numpy permite criar vetores de qualquer dimensão, de forma a completar o vetor com valores.             

* np.zeros() cria vetor com 0's                   
* np.ones() cria vetor com 1's

Para criar com valores definidos, há a função np.arange()
Esta função permite criar vetor dado um valor inicial, valor final e o passo.

* np.arange()

In [28]:
import numpy as np

a = np.zeros((3,3))
b = np.ones((1,5))
c = np.arange(2, 10, 2)

print("Função zeros: %s\n Função ones: %s\n Função arange: %s" % (a,b,c))

Função zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 Função ones: [[1. 1. 1. 1. 1.]]
 Função arange: [2 4 6 8]


Neste último caso, apenas a função np.arange() sozinha não constrói array multidimensional.

Para resolver isto, pode-se adicionar .reshape() para modificar np.arange. O argumento da função reshape é as dimensões desejadas.

In [29]:
import numpy as np

a = np.arange(0,12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Outra função intrínseca é a função np.linspace(). Esta função recebe o valor inicial, valor final e número de intervalos. Com isto, o intervalo entre o valor inicial e final será dividido no número de intervalos de forma simétrica. 

In [30]:
import numpy as np 

a = np.linspace(0,10,4)
print(a)

[ 0.          3.33333333  6.66666667 10.        ]


Por fim, a última função que permite construir arrays, só que com números aleatórios, é a função np.random().

Esta função ainda recebe outra subfunção, dependendo da forma de obter valores aleatórios. Estas subfunções podem ser binomial(), uniform(), random(), etc...

A função np.random.random pegará valores entre 0 e 1

In [31]:
import numpy as np 

a = np.random.random(3)
print(a)

[0.7737129  0.67008547 0.87138989]


#### Operações Básicas:

Operações aritméticas são aplicadas elemento por elemento

In [32]:
import numpy as np 

a = np.array([0,1,2,3])
e = np.linspace(0,10,4)
b = a + 4
c = a * 2
d = a / 3
print("Soma: %s\n Multiplicação: %s \n Divisão: %s \n Subtração de dois vetores: %s \n" % (b, c, d, e))

Soma: [4 5 6 7]
 Multiplicação: [0 2 4 6] 
 Divisão: [0.         0.33333333 0.66666667 1.        ] 
 Subtração de dois vetores: [ 0.          3.33333333  6.66666667 10.        ] 



Como as operações aritméticas são aplicadas em elementos, a multiplicação de matrizes são feitas por funções.

A função np.dot() realiza esta operação

In [33]:
import numpy as np 

A = np.linspace(0,30,15).reshape(3,5)
B = np.random.randint(0,45,15).reshape(5,3)
print(np.dot(A,B))

[[ 872.14285714  360.          550.71428571]
 [2811.42857143 1131.42857143 2157.85714286]
 [4750.71428571 1902.85714286 3765.        ]]


#### Funções Universais:

Funções universais são funções do numpy para aplicar funções matemáticas, como log, exp, etc...

In [34]:
import numpy as np

valor = 10
a = np.sqrt(valor)  #Raiz
b = np.log10(valor)
c = np.log2(valor)
d = np.sin(valor)
e = np.cos(valor)
f = np.tan(valor) #Tangente
g = np.exp(valor)
print("Raiz: %f\n Log: %f\n Log de base 2: %f\n Seno: %f\n Cosseno: %f\n Tangente: %f\n Exponencial: %f\n" %(a,b,c,d,e,f,g))

Raiz: 3.162278
 Log: 1.000000
 Log de base 2: 3.321928
 Seno: -0.544021
 Cosseno: -0.839072
 Tangente: 0.648361
 Exponencial: 22026.465795



Para a função logaritmica, pode-se definir a base diretamente na sintaxe:

np.log (base e)                                     
np.log10 (base 10)                                  
np.log2 (base 2)                                    

#### Funções de Agregação:

Funções de agregação permitem extrair dados de arrays, como máximo, média, mínimo, etc...

In [35]:
import numpy as np

a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
print("Soma: %f\n Mínimo: %f\n Máximo: %f\n Média: %f\n Desvio Padrão: %f\n" %(a.sum(),a.min(),a.max(),a.mean(),a.std()))

Soma: 15.000000
 Mínimo: 0.300000
 Máximo: 5.700000
 Média: 3.000000
 Desvio Padrão: 2.007984



Em arrays criados, pode-se acessar valores únicos separadamente.

Isto é feito por meio da indexação

In [36]:
import numpy as np

a = np.arange(10,16)
print(a[0])
print(a[-1]) #Acessa o primeiro valor em ordem inversa

10
15


Em arrays multidimensionais, é necessário especificar a posição para cada dimensão

In [37]:
import numpy as np

a = np.arange(10,19).reshape((3,3))

print(a, a[1][2])

[[10 11 12]
 [13 14 15]
 [16 17 18]] 15


#### Fatiamento:

Consiste em tomar partes do array, especificando o intervalo de posições

In [38]:
import numpy as np

a = np.arange(10,16)
print(a[1:5]) #Pega os valores das posições 1 a 5
print(a[1:5:2]) #Pega os valores das posições 1 a 5 com passo 2
print(a[::2]) #Pega todos os valores com passo 2
print(a[:5:2]) #Pega valores até a posição 5 com passo 2
print(a[:5:]) #Pega valores até a posição 5

[11 12 13 14]
[11 13]
[10 12 14]
[10 12 14]
[10 11 12 13 14]


Para arrays multidimensionais, o fatiamento segue o mesmo padrão, porém com número de colchetes igual ao número de dimensões ou com posições separadas por vírgula, 

In [39]:
import numpy as np 

a = np.arange(10,19).reshape((3,3))
print(a[:][0])
print(a[0:2,0:2])

[10 11 12]
[[10 11]
 [13 14]]


#### Iteração com Arrays:

As iterações com arrays são feitar com a função for

In [40]:
import numpy as np

a = np.arange(10,19).reshape((3,3))
for i in a:
    print(i)
for i in a.flat:
    print(i)

[10 11 12]
[13 14 15]
[16 17 18]
10
11
12
13
14
15
16
17
18


Como altenativa, o numpy oferece funções que evitam loops. Esta função é: np.apply_along_axis() e é dedicada à aplicação de funções de agregação ou funções genéricas criadas.

O parâmetro axis vale 0 ou 1, sendo 0 para cálculo de coluna por coluna e 1, para cálculo de linha por linha

In [41]:
import numpy as np

def foo(x):
    return x/2

a = np.arange(10,19).reshape((3,3))
print(np.apply_along_axis(foo, axis=1, arr=a))
print(np.apply_along_axis(foo, axis=0, arr=a))




[[5.  5.5 6. ]
 [6.5 7.  7.5]
 [8.  8.5 9. ]]
[[5.  5.5 6. ]
 [6.5 7.  7.5]
 [8.  8.5 9. ]]


#### Condições e Arrays Booleanos:

Como alternativa para filtragem de arrays, pode implementar condições para testagem de dados.

In [42]:
import numpy as np 

a = np.arange(0,5)
b = a < 2
print(b)

[ True  True False False False]


#### Manipulação de Formatos de arrays:

Arrays podem ser transformados em matrizes e vice-versa. 

* O comando reshape() transforma array em matriz
* O comando ravel() transforma matriz em array
* O comando transpose() transpõe matrizes

In [43]:
import numpy as np

a = np.arange(10,19)
b = a.reshape((3,3))
c = b.ravel()
print(a)
print(b)
print(c)

[10 11 12 13 14 15 16 17 18]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[10 11 12 13 14 15 16 17 18]


#### Joining Arrays: 

Pode-se combinar arrays para formar um único.

* Função hstack() combina vetores adicionando como colunas
* Função vstack() combina vetores aumentado 1 dimensão

In [44]:
import numpy as np

a = np.ones((3,3))
b = np.zeros((3,3))
c = np.stack((a,b))
print(c); print(np.ndim(c), np.size(c), np.shape(c))
d = np.hstack((a,b))
print(d); print(np.ndim(d), np.size(d), np.shape(d))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
3 18 (2, 3, 3)
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
2 18 (3, 6)


#### Para arrays 1D, usam-se as funções:

* Função column_stack() para juntá-los por colunas
* Função row_stack() para juntá-los por linhas

In [45]:
import numpy as np 

a = np.arange(0,5)
b = np.arange(5,10)
c = np.column_stack((a,b))
d = np.row_stack((a,b))

print(c)
print(d)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Splitting Arrays: 

Pode-se separar um array em outros.

* hsplit separa o array pela coluna
* vsplit separa o array pela linha

In [46]:
import numpy as np 

a = np.arange(16).reshape(4,4) 

[b,c] = np.hsplit(a,2)
print(b)
print(c)
[d,e] = np.vsplit(a,2)
print(d)
print(e)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


#### Para divisões não simétricas: 

Função split() recebe os parâmetros: array, divisões em linhas e colunas e axis

In [47]:
import numpy as np

a = np.arange(0,16).reshape(4,4)
[a1,a2,a3] = np.split(a, [1,3], axis=1)
print(a1)
print(a2)
print(a3)

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]


#### Conceitos Gerais:

Fazer a = c não copiará vetores, fazendo com que haja alteração nas duas variáveis.

Para copiar vetores, usar: np.copy()

In [48]:
import numpy as np 

a = np.array([1,2,3,4])
c = a.copy()
print(c)

[1 2 3 4]


#### Salvando e Abrindo dados de Arquivos Binários:

np.save('nome_do_arquivo', data) salvará o arquivo  na extensão .npy.

* Salvar: dados = np.save('nome_do_arquivo.py')       
* Abrir: dados = np.load('nome_do_arquivo.py')

#### Abrindo dados de TXT ou CSV: 

* data = np.getfromtxt('arquivo.csv', delimiter = ',', names = True )                                     
A função recebe como parãmetro o delimitador que separa os dados

#### Adicionais:

np.meshgrid gera uma grade retangular a partir de arrays 1D calculando o valor dos pontos.

* Exemplo de uso:                                     
xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))

np.c concatena dois arrays ou mais como colunas

* Exemplo de uso:
knn.predict(np.c_[xx.ravel(), yy.ravel()]) 